language: android
sudo: false
jdk:
  - oraclejdk7

env:
- TERM=dumb

before_install:
 - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.0

    # The SDK version used to compile your project
    - android-23

before_script:
    - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
    - echo yes | android update sdk --filter android-21 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

script:
    - ./gradlew assembleDebug

after_success:
- ./gradlew cobertura coveralls